Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "ubuntu/trusty64"
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.box = "ubuntu/trusty64"
  end

  config.vm.define :vm3 do |vm3|
    vm3.vm.box = "ubuntu/trusty64"
  end
end
