Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "hello.yml"
    ansible.verbose = "v"
  end
end
